# Generated by Django 4.1.3 on 2022-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=12)),
                ('student_email', models.CharField(max_length=150)),
                ('student_address', models.CharField(max_length=150)),
                ('student_place', models.CharField(max_length=50)),
            ],
        ),
    ]
